SELECT        
    BR.ID AS BATCH_RUN_ID, 
    BR.NAME AS BATCH_RUN_NAME, 
    BR.SCHEDULED_START_DATE_TIME, 
    BR.START_DATE_TIME, 
    BR.END_DATE_TIME, 
    BR.QUANTITY, 
    BRS.ID AS BATCH_RUN_STEP_ID, 
    BRSE.ID AS BATCH_RUN_STEP_EQUIPMENT_ID, 
    BRSP.ID AS BATCH_RUN_STEP_PARAMETER_ID, 
    BRSP.NAME AS BATCH_RUN_STEP_PARAMETER_NAME, 
    BRSP.EXPECTED_VALUE, 
    BRSP.ACTUAL_VALUE, 
    FA.ID AS FACULTY_ASSET_ID, 
    FA.NAME AS FACULTY_ASSET_NAME, 
    FAT.NAME AS FACILITY_ASSET_TYPE_NAME, 
    FAT.ID AS FACILITY_ASSET_TYPE_ID, 
    FAT.CATEGORY AS FACILITY_ASSET_TYPE_CATAGORY, 
    BTSP.ID AS BATCH_TEMPLATE_STEP_PARAMETER_ID, 
    BTSP.NAME AS BATCH_TEMPLATE_STEP_PARAMETER_NAME, 
    BTSP.PARAMETER_TYPE AS BATCH_TEMPLATE_STEP_PARAMETER_PARAMETER_TYPE, 
    FBSPT.STEP_PARAMETER_TRANSACTIONS_DATE_TIME, 
    FBSPT.STEP_PARAMETER_TRANSACTIONS_PERSONNEL_LINK_ID, 
    FBSPT.STEP_PARAMETER_TRANSACTIONS_VALUE_TYPE_ENUM, 
    FBSPT.APPROVED_PERSONNEL_USER_NAME,
    FA.DEPARTMENT AS FACILITY_ASSET_DEPARTMENT, 
    FA.FINANCE_ASSET_ID, 
    FA.DEVICE_UNIQUE_ID, 
    BRS.START_DATE_TIME AS BATCH_RUN_STEP_START_DATE_TIME, 
    BRS.END_DATE_TIME AS BATCH_RUN_STEP_END_DATE_TIME, 
    P.USER_NAME AS DONE_BY_PERSONNEL_USER_NAME, 
    ILAF.INTERNAL_LOCATION_LINK_ID AS INTERNAL_LOCATION_ID, 
    IL.NAME AS INTERNAL_LOCATION_NAME,
    IL.LOCATION_CODE AS INTERNAL_LOCATION_CODE, 
    BRS.NAME AS STEP_NAME
  --  CV.LAST_UPDATE_BY
FROM            
    UEIOS_V3.dbo.BATCH_RUN BR
    INNER JOIN UEIOS_V3.dbo.BATCH_RUN_STEP BRS ON BRS.BATCH_RUN_ID = BR.ID AND ISNULL(BRS.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_INTERNAL_V3.dbo.CHECKLIST_RELATIONSHIPS CR ON CR.BATCH_RUN_STEP_ID = BRS.ID AND ISNULL(CR.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_MAPPING CCM ON CCM.ID = CR.CHECKLIST_MAPPING_ID AND ISNULL(CCM.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST CH ON CH.ID = CCM.CHECKLIST_LINK_ID AND ISNULL(CH.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_TEMPLATE CT ON CT.ID = CH.CHECKLIST_TEMPLATE_LINK_ID AND ISNULL(CT.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_CATEGORY CCAT ON CCAT.ID = CT.CHECKLIST_CATEGORY_LINK_ID AND ISNULL(CCAT.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_GROUP CG ON CG.CHECKLIST_TEMPLATE_LINK_ID = CT.ID AND ISNULL(CG.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_MAPPING_GROUP CMG ON CMG.CHECKLIST_MAPPING_LINK_ID = CCM.ID AND CMG.CHECKLIST_GROUP_LINK_ID = CG.ID AND ISNULL(CMG.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_ITEM CI ON CI.CHECKLIST_GROUP_LINK_ID = CG.ID AND ISNULL(CI.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_MAPPING_ITEM CMI ON CMI.CHECKLIST_ITEM_LINK_ID = CI.ID AND CMI.CHECKLIST_MAPPING_GROUP_LINK_ID = CMG.ID AND ISNULL(CMI.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_COLUMN CC ON CC.CHECKLIST_TEMPLATE_LINK_ID = CT.ID AND ISNULL(CC.IS_DELETED, 0) = 0
    LEFT OUTER JOIN UEIOS_V4.dbo.CHK_CHECKLIST_VALUE CV ON CV.CHECKLIST_COLUMN_LINK_ID = CC.ID AND CV.CHECKLIST_ITEM_LINK_ID = CI.ID AND CV.CHECKLIST_MAPPING_ITEM_LINK_ID = CMI.ID AND ISNULL(CV.IS_DELETED, 0) = 0
    LEFT JOIN UEIOS_V3.dbo.BATCH_RUN_STEP_EQUIPMENT BRSE ON BRS.ID = BRSE.BATCH_RUN_STEP_ID 
    INNER JOIN UEIOS_V3.dbo.MAINTENANCE_SCHEDULE_BATCH_RUN_RELATIONSHIP MSBR ON BR.ID = MSBR.BATCH_RUN_ID
    INNER JOIN UEIOS_V3.dbo.MAINTENANCE_SCHEDULE MS ON MSBR.MAINTENANCE_SCHEDULE_ID = MS.ID
    LEFT JOIN UEIOS_V3.dbo.BATCH_RUN_STEP_PARAMETER BRSP ON BRS.ID = BRSP.BATCH_RUN_STEP_ID 
    LEFT JOIN UEIOS_V3.dbo.BATCH_TEMPLATE_STEP_PARAMETER BTSP ON BRSP.BATCH_TEMPLATE_STEP_PARAMETER_ID = BTSP.ID 
    LEFT JOIN UEIOS_V3.dbo.FACILITY_ASSET FA ON MS.FACILITY_ASSET_ID = FA.ID 
    LEFT OUTER JOIN UEIOS_V3.dbo.INTERNAL_LOCATION IL
    INNER JOIN UEIOS_V3.dbo.INTERNAL_LOCATION_FACILITY_ASSET_RELATIONSHIP ILAF ON IL.ID = ILAF.INTERNAL_LOCATION_LINK_ID 
    ON FA.ID = ILAF.FACILITY_ASSET_LINK_ID 
    LEFT JOIN UEIOS_V3.dbo.FACILITY_ASSET_TYPE FAT ON FAT.ID = FA.FACILITY_ASSET_TYPE_ID 
    LEFT OUTER JOIN (
        SELECT        
            BRSP1.ID AS STEP_PARAMETER_ID, 
            BRSPT.DATE_TIME AS STEP_PARAMETER_TRANSACTIONS_DATE_TIME, 
            BRSPT.PERSONNEL_LINK_ID AS STEP_PARAMETER_TRANSACTIONS_PERSONNEL_LINK_ID, 
            BRSPT.VALUE_TYPE_ENUM AS STEP_PARAMETER_TRANSACTIONS_VALUE_TYPE_ENUM, 
            P1.USER_NAME AS APPROVED_PERSONNEL_USER_NAME
        FROM            
            UEIOS_V3.dbo.PERSONNEL P1
            INNER JOIN UEIOS_V3.dbo.BATCH_RUN_STEP_PARAMETER_TRANSACTIONS BRSPT ON P1.ID = BRSPT.PERSONNEL_LINK_ID 
            RIGHT OUTER JOIN UEIOS_V3.dbo.BATCH_RUN_STEP_PARAMETER BRSP1
            INNER JOIN UEIOS_V3.dbo.BATCH_TEMPLATE_STEP_PARAMETER BTSP1 ON BRSP1.BATCH_TEMPLATE_STEP_PARAMETER_ID = BTSP1.ID 
            ON BRSPT.BATCH_RUN_STEP_PARAMETER_LINK_ID = BRSP1.ID
        WHERE        
            ISNULL(BRSP1.IS_DELETED, 0) = 0 
            AND ISNULL(BRSPT.IS_DELETED, 0) = 0 
            AND BTSP1.PARAMETER_TYPE = 4 
            AND ISNULL(BTSP1.IS_DELETED, 0) = 0 
            AND ISNULL(P1.IS_DELETED, 0) = 0
    ) AS FBSPT ON BRSP.ID = FBSPT.STEP_PARAMETER_ID 
    LEFT OUTER JOIN (
        SELECT        
            BRSE1.TRANSACTION_OWNER_PERSONNEL_ID, 
            BRSE1.BATCH_RUN_STEP_EQUIPMENT_ID
        FROM            
            (SELECT        
                MAX(ID) AS MAX_ID, 
                BATCH_RUN_STEP_EQUIPMENT_ID
            FROM            
                UEIOS_V3.dbo.BATCH_RUN_STEP_EQUIPMENT_TRANSACTIONS
            WHERE        
                TRANSACTION_NOTES LIKE 'SDT_ACTIVE'
            GROUP BY 
                BATCH_RUN_STEP_EQUIPMENT_ID
            ) AS BRSE_MAX_TRANSACTION_FOR_SDT_ACTIVE
            INNER JOIN UEIOS_V3.dbo.BATCH_RUN_STEP_EQUIPMENT_TRANSACTIONS BRSE1 ON BRSE_MAX_TRANSACTION_FOR_SDT_ACTIVE.MAX_ID = BRSE1.ID
    ) AS LAST_PERSONNEL_FOR_SDT_ACTIVE 
    LEFT OUTER JOIN UEIOS_V3.dbo.PERSONNEL P ON LAST_PERSONNEL_FOR_SDT_ACTIVE.TRANSACTION_OWNER_PERSONNEL_ID = P.ID 
    ON BRSE.ID = LAST_PERSONNEL_FOR_SDT_ACTIVE.BATCH_RUN_STEP_EQUIPMENT_ID
WHERE        
    ISNULL(BRS.IS_DELETED, 0) = 0 
    AND ISNULL(BR.IS_DELETED, 0) = 0 
    AND ISNULL(BRSE.IS_DELETED, 0) = 0 
    AND ISNULL(BRSP.IS_DELETED, 0) = 0 
    AND ISNULL(FA.IS_DELETED, 0) = 0 
    AND ISNULL(ILAF.IS_DELETED, 0) = 0 
    AND ISNULL(IL.IS_DELETED, 0) = 0 
   -- AND ISNULL(BTS.IS_DELETED, 0) = 0 
    --AND BR.BATCH_RUN_TYPE = 3 
    AND ISNULL(MS.IS_DELETED, 0) = 0 
    AND ISNULL(MSBR.IS_DELETED, 0) = 0;
